// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdpdtgvxhhpinwskhaqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkcGR0Z3Z4aGhwaW53c2toYXF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTY2MDMsImV4cCI6MjA2NTkzMjYwM30.wUFOifIdr4pGtppxeHWVbQypmCGF7rT0xjbiOciv-fo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});